export const productos = [
    {
        title: "Torta Chocolate",
        price: 1500,
        image: "torta_choco.jpg",
        description: '',
        category: "tortas",
        stock: 20,
        id: 1,
    },
    {
        title: "Torta Alfajor",
        price: 1200,
        image: "torta_alfajor.jpg",
        description: '',
        category: "tortas",
        stock: 10,
        id: 2,
    },
    {
        title: "Lemon Pie",
        price: 1000,
        image: "lemon pie2.jpeg",
        description: '',
        category: "tortas",
        stock: 5,
        id: 3,
    },
    {
        title: "Torta Frutilla",
        price: 1500,
        image: "torta_frutillas.jpg",
        description: '',
        category: "tortas",
        stock: 12,
        id: 4,
    },
    {
        title: "Alfajor Chocolate",
        price: 120,
        image: "choco.jpg",
        description: '',
        category: "alfajores",
        stock: 13,
        id: 11,
    },
    {
        title: "Alfajor Vainilla",
        price: 120,
        image: "vainilla.jpg",
        description: '',
        category: "alfajores",
        stock: 10,
        id: 12,
    },
    {
        title: "Alfajor Membrillo",
        price: 100,
        image: "membrillo.jpg",
        description: '',
        category: "alfajores",
        stock: 8,
        id: 13,
    },
    {
        title: "Alfajor Frutilla",
        price: 130,
        image: "frutilla.jpg",
        description: '',
        category: "alfajores",
        stock: 12,
        id: 14,
    },
]